<a href="https://colab.research.google.com/github/W-Srikongpan/DPDM2023/blob/main/Frequent_Patterns_(Association_Rules).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import os
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
data = pd.read_csv('/content/drive/MyDrive/DPDM2023_DATA/reduced_marketbasket.csv', encoding='latin-1')
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/01/2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/01/2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/09/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/09/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/09/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/09/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/09/2011 12:50,4.95,12680.0,France

Group by InvoiceNo and StockCode

In [6]:
data.groupby('InvoiceNo').max()

,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
InvoiceNo,,,,,,,
536365,85123A,WHITE METAL LANTERN,8,12/01/2010 08:26,7.65,17850.0,United Kingdom
536366,22633,HAND WARMER UNION JACK,6,12/01/2010 08:28,1.85,17850.0,United Kingdom
536367,84969,RECIPE BOX WITH METAL HEART,32,12/01/2010 08:34,9.95,13047.0,United Kingdom
536368,22960,YELLOW COAT RACK PARIS FASHION,6,12/01/2010 08:34,4.95,13047.0,United Kingdom
536369,21756,BATH BUILDING BLOCK WORD,3,12/01/2010 08:35,5.95,13047.0,United Kingdom
...,...,...,...,...,...,...,...
C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,12/09/2011 09:27,2.08,16446.0,United Kingdom
C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,12/09/2011 09:57,1.95,14397.0,United Kingdom
C581499,M,Manual,-1,12/09/2011 10:28,224.69,15498.0,United Kingdom
C581568,21258,VICTORIAN SEWING BOX LARGE,-5,12/09/2011 11:57,10.95,15311.0,United Kingdom
C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,12/09/2011 11:58,1.25,17315.0,United Kingdom

In [5]:
data.groupby('InvoiceNo')['StockCode'].apply(list)

InvoiceNo
536365     [85123A, 71053, 84406B, 84029G, 84029E, 22752,...
536366                                        [22633, 22632]
536367     [84879, 22745, 22748, 22749, 22310, 84969, 226...
536368                          [22960, 22913, 22912, 22914]
536369                                               [21756]
                                 ...
C581484                                              [23843]
C581490                                       [22178, 23144]
C581499                                                  [M]
C581568                                              [21258]
C581569                                       [84978, 20979]
Name: StockCode, Length: 25900, dtype: object

In [7]:
data.groupby('Country').count()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID
Country,,,,,,,
Australia,1259,1259,1259,1259,1259,1259,1259
Austria,401,401,401,401,401,401,401
Bahrain,19,19,19,19,19,19,17
Belgium,2069,2069,2069,2069,2069,2069,2069
Brazil,32,32,32,32,32,32,32
Canada,151,151,151,151,151,151,151
Channel Islands,758,758,758,758,758,758,758
Cyprus,622,622,622,622,622,622,622
Czech Republic,30,30,30,30,30,30,30
Denmark,389,389,389,389,389,389,389
EIRE,8196,8196,8196,8196,8196,8196,7485
European Community,61,61,61,61,61,61,61
Finland,695,695,695,695,695,695,695
France,8557,8557,8557,8557,8557,8557,8491
Germany,9495,9495,9495,9495,9495,9495,9495
Greece,146,146,146,146,146,146,146
Hong Kong,288,288,288,288,288,288,0
Iceland,182,182,182,182,182,182,182
Israel,297,297,297,297,297,297,250
Italy,803,803,803,803,803,803,803
Japan,358,358,358,358,358,358,358
Lebanon,45,45,45,45,45,45,45
Lithuania,35,35,35,35,35,35,35
Malta,127,127,127,127,127,127,127
Netherlands,2371,2371,2371,2371,2371,2371,2371
Norway,1086,1086,1086,1086,1086,1086,1086
Poland,341,341,341,341,341,341,341
Portugal,1519,1519,1519,1519,1519,1519,1480
RSA,58,58,58,58,58,58,58
Saudi Arabia,10,10,10,10,10,10,10
Singapore,229,229,229,229,229,229,229
Spain,2533,2533,2533,2533,2533,2533,2533
Sweden,462,462,462,462,462,462,462
Switzerland,2002,2002,2002,2002,2002,2002,1877
USA,291,291,291,291,291,291,291
United Arab Emirates,68,68,68,68,68,68,68
United Kingdom,495478,495478,494024,495478,495478,495478,361878
Unspecified,446,446,446,446,446,446,244

In [8]:
transactions = data.groupby('CustomerID')['StockCode'].apply(list)
transactions

CustomerID
12346.0                                       [23166, 23166]
12347.0    [85116, 22375, 71477, 22492, 22771, 22772, 227...
12348.0    [84992, 22951, 84991, 84991, 21213, 21213, 226...
12349.0    [23112, 23460, 21564, 21411, 21563, 22131, 221...
12350.0    [21908, 22412, 79066K, 79191C, 22348, 84086C, ...
                                 ...
18280.0    [82484, 22180, 22467, 22725, 22727, 22495, 223...
18281.0    [22037, 22716, 22028, 23007, 23008, 23209, 22467]
18282.0    [21270, 23187, 23295, 22089, 21108, 21109, 224...
18283.0    [22356, 20726, 22384, 22386, 20717, 20718, 850...
18287.0    [22755, 22754, 22753, 22756, 22758, 22757, 227...
Name: StockCode, Length: 4372, dtype: object

In [10]:
pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5955 sha256=76e9f5cbaafdc5f078955cfa1833092901b7714f8047cc0a69bfd52e21a32dcc
  Stored in directory: /root/.cache/pip/wheels/c4/1a/79/20f55c470a50bb3702a8cb7c94d8ada15573538c7f4baebe2d
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [15]:
from apyori import apriori
frequentitemsets = list(apriori(transactions, min_support = 0.025))

In [16]:
len(frequentitemsets)

4318

In [17]:
frequentitemsets[0]

RelationRecord(items=frozenset({'15036'}), support=0.04437328453796889, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'15036'}), confidence=0.04437328453796889, lift=1.0)])

In [ ]:
min_sup = 0.03
frequentitemsets = list(apriori(transactions, min_support = min_sup))
if

In [26]:
set(data[(data['StockCode']== '22697')|(data['StockCode']== '22386')|(data['StockCode']== '22699')]['Description'])

{'GREEN REGENCY TEACUP AND SAUCER',
 'JUMBO BAG PINK POLKADOT',
 'ROSES REGENCY TEACUP AND SAUCER '}

In [29]:
data[(data['StockCode']== '22697')|(data['StockCode']== '22699')]#['InvoiceNo']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1077,536523,22699,ROSES REGENCY TEACUP AND SAUCER,6,12/01/2010 12:50,2.95,12868.0,United Kingdom
1086,536524,22697,GREEN REGENCY TEACUP AND SAUCER,6,12/01/2010 12:51,2.95,17572.0,United Kingdom
1193,536530,22699,ROSES REGENCY TEACUP AND SAUCER,4,12/01/2010 13:21,2.95,17905.0,United Kingdom
1644,536544,22697,GREEN REGENCY TEACUP AND SAUCER,6,12/01/2010 14:32,5.91,NaN,United Kingdom
1645,536544,22699,ROSES REGENCY TEACUP AND SAUCER,2,12/01/2010 14:32,5.91,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
540986,581492,22699,ROSES REGENCY TEACUP AND SAUCER,2,12/09/2011 10:03,5.79,NaN,United Kingdom
541218,581495,22699,ROSES REGENCY TEACUP AND SAUCER,12,12/09/2011 10:20,2.95,14051.0,United Kingdom
541220,581495,22697,GREEN REGENCY TEACUP AND SAUCER,12,12/09/2011 10:20,2.95,14051.0,United Kingdom
541449,581498,22697,GREEN REGENCY TEACUP AND SAUCER,6,12/09/2011 10:26,5.79,NaN,United Kingdom
541451,581498,22699,ROSES REGENCY TEACUP AND SAUCER,6,12/09/2011 10:26,5.79,NaN,United Kingdom