<a href="https://colab.research.google.com/github/W-Srikongpan/DPDM2023/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [4]:
from google.colab import drive # conect google drive
drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
project_df = pd.read_csv('/content/drive/MyDrive/DPDM2023_DATA/opendata_unittype-2.csv')
project_df.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
0,37586,unittype_35602,project_15270,Studio,2,Condo,คอนโด,NaN,30.0,3700000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:56,2020-10-14 20:21:01,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11
1,9427,unittype_4487,project_1476,ภัทรสิน,3,Townhome,ทาวน์โฮม,NaN,NaN,2000000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:17,2020-10-14 00:53:00,baania,https://baania.com/th/project/บ้านสวนทรัพย์ธาน...,2023-06-11
2,12994,unittype_37624,project_16674,Type B,3,Townhome,ทาวน์โฮม,24.0,96.0,NaN,...,NaN,NaN,NaN,NaN,NaN,2022-09-09 15:30:02,2022-09-09 15:03:18,baania,https://baania.com/th/project/สกายไลน์-อมตะ-16...,2023-06-11
3,19073,62286afcc74d880014871357,622861f7aae18f00134066d6,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,NaN,NaN,1000000.0,...,1.0,NaN,NaN,NaN,NaN,2022-03-09 16:30:04,2022-03-09 16:17:44,baania,https://baania.com/th/project/รุ่งเรืองทรัพย์ว...,2023-06-11
4,10907,unittype_8344,project_2821,2 Bedroom (ขายแล้ว),2,Condo,คอนโด,NaN,48.0,4200000.0,...,1.0,1.0,NaN,NaN,NaN,2021-11-12 13:24:53,2020-10-16 16:46:17,baania,https://baania.com/th/project/เดอะ-เทมโป-แกรนด...,2023-06-11

###6. What is average price of the property that has usable area (area_usable_min) between 50-100 sqm?

In [65]:
area_usable = project_df[['area_usable_min','price_min']]

In [63]:
area_usable = project_df[['area_usable_min','price_min']]
selected_rows = area_usable.loc[(area_usable['area_usable_min'] >= 50) & (area_usable['area_usable_min'] <= 50) ]
a = selected_rows.dropna()

In [64]:
sum(a['price_min'])
len(a['price_min'])
average = sum(a['price_min'])/len(a['price_min'])
print(f"Average: {average}")

Average: 3607233.537688442

In [ ]:
project_df.describe()

In [ ]:
project_df.isnull()

In [ ]:
project_df.isnull().any()

In [ ]:
project_df.isnull().all() # .all() เอาค่าความจริงใน column มา and กัน

##Drop

In [73]:
project_df.shape

(35123, 28)

In [75]:
unit_df = pd.read_csv('/content/drive/MyDrive/DPDM2023_DATA/opendata_unittype-2.csv')
unit_df.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
0,37586,unittype_35602,project_15270,Studio,2,Condo,คอนโด,NaN,30.0,3700000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:56,2020-10-14 20:21:01,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11
1,9427,unittype_4487,project_1476,ภัทรสิน,3,Townhome,ทาวน์โฮม,NaN,NaN,2000000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:17,2020-10-14 00:53:00,baania,https://baania.com/th/project/บ้านสวนทรัพย์ธาน...,2023-06-11
2,12994,unittype_37624,project_16674,Type B,3,Townhome,ทาวน์โฮม,24.0,96.0,NaN,...,NaN,NaN,NaN,NaN,NaN,2022-09-09 15:30:02,2022-09-09 15:03:18,baania,https://baania.com/th/project/สกายไลน์-อมตะ-16...,2023-06-11
3,19073,62286afcc74d880014871357,622861f7aae18f00134066d6,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,NaN,NaN,1000000.0,...,1.0,NaN,NaN,NaN,NaN,2022-03-09 16:30:04,2022-03-09 16:17:44,baania,https://baania.com/th/project/รุ่งเรืองทรัพย์ว...,2023-06-11
4,10907,unittype_8344,project_2821,2 Bedroom (ขายแล้ว),2,Condo,คอนโด,NaN,48.0,4200000.0,...,1.0,1.0,NaN,NaN,NaN,2021-11-12 13:24:53,2020-10-16 16:46:17,baania,https://baania.com/th/project/เดอะ-เทมโป-แกรนด...,2023-06-11

In [76]:
unit_df.shape

(43374, 28)

In [77]:
project_df.dropna()

Empty DataFrame
Columns: [row_number, unittype_id, project_id, name_th, propertytype_id, propertytype_name_en, propertytype_name_th, area_total_min_wa, area_usable_min, price_min, count_airconditioner, count_elevator, count_floor_internal, count_parking, count_room_bath, count_room_bed, count_room_dinning, count_room_guest, count_room_kitchen, count_room_living, count_room_maid, count_room_storage, count_room_utility, date_created, date_updated, source, url_unittype, day]
Index: []

[0 rows x 28 columns]

In [78]:
unit_df.dropna()

Empty DataFrame
Columns: [row_number, unittype_id, project_id, name_th, propertytype_id, propertytype_name_en, propertytype_name_th, area_total_min_wa, area_usable_min, price_min, count_airconditioner, count_elevator, count_floor_internal, count_parking, count_room_bath, count_room_bed, count_room_dinning, count_room_guest, count_room_kitchen, count_room_living, count_room_maid, count_room_storage, count_room_utility, date_created, date_updated, source, url_unittype, day]
Index: []

[0 rows x 28 columns]

In [79]:
project_df.dropna(axis=1)

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,price_min,date_created,date_updated,source,url_unittype,day
0,37586,unittype_35602,project_15270,Studio,2,Condo,คอนโด,3700000.0,2021-11-12 13:22:56,2020-10-14 20:21:01,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11
1,9427,unittype_4487,project_1476,ภัทรสิน,3,Townhome,ทาวน์โฮม,2000000.0,2021-11-12 13:20:17,2020-10-14 00:53:00,baania,https://baania.com/th/project/บ้านสวนทรัพย์ธาน...,2023-06-11
3,19073,62286afcc74d880014871357,622861f7aae18f00134066d6,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,1000000.0,2022-03-09 16:30:04,2022-03-09 16:17:44,baania,https://baania.com/th/project/รุ่งเรืองทรัพย์ว...,2023-06-11
4,10907,unittype_8344,project_2821,2 Bedroom (ขายแล้ว),2,Condo,คอนโด,4200000.0,2021-11-12 13:24:53,2020-10-16 16:46:17,baania,https://baania.com/th/project/เดอะ-เทมโป-แกรนด...,2023-06-11
5,26056,unittype_22238,project_2742,Garnet,3,Townhome,ทาวน์โฮม,4900000.0,2021-11-12 13:22:38,2020-10-14 18:51:56,baania,https://baania.com/th/project/เดอะ-บัลโคนี่-โฮ...,2023-06-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43369,9507,unittype_5086,project_1635,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,880000.0,2022-10-19 11:30:05,2022-10-19 11:17:08,baania,https://baania.com/th/project/บ้านคุรุสภา-นครร...,2023-06-11
43370,23721,unittype_15644,project_6109,บ้านเดี่ยวสองชั้น,1,Detached House,บ้าน,2400000.0,2021-11-12 13:24:19,2020-10-14 23:03:19,baania,https://baania.com/th/project/บ้านเต็มสิริ-1-6...,2023-06-11
43371,31551,unittype_21385,project_8392,อาคารพาณิชย์สี่ชั้น type B,4,Commercial,อาคารพาณิชย์,13000000.0,2021-11-12 13:19:31,2020-10-14 00:38:09,baania,https://baania.com/th/project/พระเงิน-เพลส-839...,2023-06-11
43372,29837,unittype_26243,project_10566,ทาวน์โฮมสามชั้น,3,Townhome,ทาวน์โฮม,2600000.0,2020-12-04 10:47:10,2020-10-16 16:33:56,baania,https://baania.com/th/project/บ้านไทยวิลล่า-ศร...,2023-06-11
43373,9465,unittype_35686,project_15298,2 Bedroom,2,Condo,คอนโด,3490000.0,2023-02-28 11:00:15,2023-02-28 10:41:37,baania,https://baania.com/th/project/แกรนด์-คอนโดมิเน...,2023-06-11

In [67]:
project_df_droped = project_df.dropna(subset=['propertytype_name_en','price_min'])

In [68]:
project_df.dropna(subset=['propertytype_name_en','price_min']).isnull().any()

row_number              False
unittype_id             False
project_id              False
name_th                 False
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa        True
area_usable_min          True
price_min               False
count_airconditioner     True
count_elevator           True
count_floor_internal     True
count_parking            True
count_room_bath          True
count_room_bed           True
count_room_dinning       True
count_room_guest         True
count_room_kitchen       True
count_room_living        True
count_room_maid          True
count_room_storage       True
count_room_utility       True
date_created            False
date_updated            False
source                  False
url_unittype            False
day                     False
dtype: bool

In [70]:
#update data
project_df.dropna(subset=['propertytype_name_en','price_min'],inplace=True)

In [71]:
project_df.isnull().any()

row_number              False
unittype_id             False
project_id              False
name_th                 False
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa        True
area_usable_min          True
price_min               False
count_airconditioner     True
count_elevator           True
count_floor_internal     True
count_parking            True
count_room_bath          True
count_room_bed           True
count_room_dinning       True
count_room_guest         True
count_room_kitchen       True
count_room_living        True
count_room_maid          True
count_room_storage       True
count_room_utility       True
date_created            False
date_updated            False
source                  False
url_unittype            False
day                     False
dtype: bool

## Example

###1.
 remove missing values by dropping column,

###2.

#Replace missing value

##Replace missing value with appropriate value(introduce a new class, up to you)

##Replace missing value with mean of the sub-group

In [ ]:
set(unit_df['propertytype_name_en'])


#Concatenate

##concatenate table in the Y-axis (add more data point)

##concatenate table in the X-axis (adding features to the data)

###Ex. map the district from the project table to the unitale

In [84]:
merged_df = unit_df.merge(project_df,left_on='project_id',right_on='project_id')
merged_df.head()

,row_number_x,unittype_id_x,project_id,name_th_x,propertytype_id_x,propertytype_name_en_x,propertytype_name_th_x,area_total_min_wa_x,area_usable_min_x,price_min_x,...,count_room_kitchen_y,count_room_living_y,count_room_maid_y,count_room_storage_y,count_room_utility_y,date_created_y,date_updated_y,source_y,url_unittype_y,day_y
0,37586,unittype_35602,project_15270,Studio,2,Condo,คอนโด,NaN,30.0,3700000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:56,2020-10-14 20:21:01,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11
1,37586,unittype_35602,project_15270,Studio,2,Condo,คอนโด,NaN,30.0,3700000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:56,2020-10-14 20:21:00,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11
2,37586,unittype_35602,project_15270,Studio,2,Condo,คอนโด,NaN,30.0,3700000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:56,2020-10-14 20:21:01,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11
3,37585,unittype_35604,project_15270,2 Bedroom,2,Condo,คอนโด,NaN,55.0,5562000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:56,2020-10-14 20:21:01,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11
4,37585,unittype_35604,project_15270,2 Bedroom,2,Condo,คอนโด,NaN,55.0,5562000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:56,2020-10-14 20:21:00,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11

In [ ]:
unit_df['district_name_en'] = unit_df['project_id'].map(project_df.set_index('project_id')['district_name_en'])

In [87]:
project_df.isnull().any()

row_number              False
unittype_id             False
project_id              False
name_th                 False
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa        True
area_usable_min          True
price_min               False
count_airconditioner     True
count_elevator           True
count_floor_internal     True
count_parking            True
count_room_bath          True
count_room_bed           True
count_room_dinning       True
count_room_guest         True
count_room_kitchen       True
count_room_living        True
count_room_maid          True
count_room_storage       True
count_room_utility       True
date_created            False
date_updated            False
source                  False
url_unittype            False
day                     False
dtype: bool

#Create pandas df & save pandas df

##Create table

##Dict-Row

In [88]:
sale = [{'account':'Jones LLC','Jan':150,'Feb':200,'Mar':140},
        {'account':'Alpha Co','Jan':200,'Feb':210,'Mar':215},
        {'account':'Blue Inc','Jan':50,'Feb':90,'Mar':95}
]

sale_tb1 = pd.DataFrame(sale)
sale_tb1

     account  Jan  Feb  Mar
0  Jones LLC  150  200  140
1   Alpha Co  200  210  215
2   Blue Inc   50   90   95

##Dict-Column

In [89]:
sales = { 'account':['Jones LLC','Alpha Co','Blue Inc'],
          'Jan'    :[150,200,50],
          'Feb'    :[200,210,90],
          'Mar'    :[140,215,90]
}
sale_tb2 = pd.DataFrame.from_dict(sales)
sale_tb2

     account  Jan  Feb  Mar
0  Jones LLC  150  200  140
1   Alpha Co  200  210  215
2   Blue Inc   50   90   95

##List-Row

In [91]:
sale = [['Jones LLC',150,200,140],
        ['Alpha Co',200,210,215],
        ['Blue Inc',50,90,90]]
labels = ['account','Jan','Feb','Mar']

sale_tb3 =

NameError: ignored