<a href="https://colab.research.google.com/github/W-Srikongpan/DPDM2023/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from google.colab import drive # conect google drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
project_df = pd.read_csv('/content/drive/MyDrive/DPDM2023_DATA/opendata_unittype-2.csv')
project_df.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
0,37586,unittype_35602,project_15270,Studio,2,Condo,คอนโด,NaN,30.0,3700000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:56,2020-10-14 20:21:01,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11
1,9427,unittype_4487,project_1476,ภัทรสิน,3,Townhome,ทาวน์โฮม,NaN,NaN,2000000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:17,2020-10-14 00:53:00,baania,https://baania.com/th/project/บ้านสวนทรัพย์ธาน...,2023-06-11
2,12994,unittype_37624,project_16674,Type B,3,Townhome,ทาวน์โฮม,24.0,96.0,NaN,...,NaN,NaN,NaN,NaN,NaN,2022-09-09 15:30:02,2022-09-09 15:03:18,baania,https://baania.com/th/project/สกายไลน์-อมตะ-16...,2023-06-11
3,19073,62286afcc74d880014871357,622861f7aae18f00134066d6,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,NaN,NaN,1000000.0,...,1.0,NaN,NaN,NaN,NaN,2022-03-09 16:30:04,2022-03-09 16:17:44,baania,https://baania.com/th/project/รุ่งเรืองทรัพย์ว...,2023-06-11
4,10907,unittype_8344,project_2821,2 Bedroom (ขายแล้ว),2,Condo,คอนโด,NaN,48.0,4200000.0,...,1.0,1.0,NaN,NaN,NaN,2021-11-12 13:24:53,2020-10-16 16:46:17,baania,https://baania.com/th/project/เดอะ-เทมโป-แกรนด...,2023-06-11

#Quiz 4

##6. What is average price of the property that has usable area (area_usable_min) between 50-100 sqm?

In [4]:
area_usable = project_df[['area_usable_min','price_min']]

In [5]:
area_usable = project_df[['area_usable_min','price_min']]
selected_rows = area_usable.loc[(area_usable['area_usable_min'] >= 50) & (area_usable['area_usable_min'] <= 100) ]
a = selected_rows.dropna()

In [6]:
sum(a['price_min'])
len(a['price_min'])
average = sum(a['price_min'])/len(a['price_min'])
print(f"Average: {average}")

Average: 3854886.406927922

#Data Cleaning

##Dealing with missing data

###1) Check missing data

In [7]:
project_df.shape #ตรวจสอบขนาด

(43374, 28)

In [8]:
project_df.describe() #แสดงข้อมูลพื้นฐาน

,row_number,propertytype_id,area_total_min_wa,area_usable_min,price_min,count_airconditioner,count_elevator,count_floor_internal,count_parking,count_room_bath,count_room_bed,count_room_dinning,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility
count,43374.000000,43374.000000,3148.000000,38139.000000,3.512300e+04,1759.000000,0.0,30387.000000,24462.000000,41741.000000,41543.000000,13425.000000,12731.000000,20018.000000,10007.000000,2110.000000,4012.000000,887.000000
mean,21687.500000,1032.336446,44.888517,141.057229,5.615888e+06,2.459352,NaN,1.962616,1.865547,2.335593,2.550995,1.002160,1.011939,1.018134,1.058459,1.050237,1.055085,1.055242
std,12521.139625,4415.313079,21.790766,114.586026,1.145051e+07,1.501013,NaN,0.644954,0.768668,1.193849,1.164172,0.048007,0.111473,0.134927,0.272829,0.231140,0.271117,0.269380
min,1.000000,1.000000,1.000000,0.030000,1.000000e+05,1.000000,NaN,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,10844.250000,1.000000,23.000000,60.000000,1.950000e+06,1.000000,NaN,2.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,21687.500000,2.000000,50.000000,126.000000,3.170000e+06,2.000000,NaN,2.000000,2.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,32530.750000,3.000000,60.000000,180.000000,5.300000e+06,3.000000,NaN,2.000000,2.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,43374.000000,20000.000000,335.000000,4350.000000,5.800000e+08,10.000000,NaN,9.000000,10.000000,66.000000,10.000000,3.000000,3.000000,3.000000,5.000000,4.000000,5.000000,4.000000

In [9]:
project_df.isnull() #check null

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
0,False,False,False,False,False,False,False,True,False,False,...,True,True,True,True,True,False,False,False,False,False
1,False,False,False,False,False,False,False,True,True,False,...,True,True,True,True,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,True,...,True,True,True,True,True,False,False,False,False,False
3,False,False,False,False,False,False,False,True,True,False,...,False,True,True,True,True,False,False,False,False,False
4,False,False,False,False,False,False,False,True,False,False,...,False,False,True,True,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43369,False,False,False,False,False,False,False,True,True,False,...,False,True,True,True,True,False,False,False,False,False
43370,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,False,False,False,False,False
43371,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,False,False,False,False,False
43372,False,False,False,False,False,False,False,True,False,False,...,True,False,True,True,True,False,False,False,False,False
43373,False,False,False,False,False,False,False,True,False,False,...,False,False,True,True,True,False,False,False,False,False

In [10]:
project_df.isnull().any() # .any() apply OR operation to every logic value column-wise

row_number              False
unittype_id             False
project_id              False
name_th                 False
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa        True
area_usable_min          True
price_min                True
count_airconditioner     True
count_elevator           True
count_floor_internal     True
count_parking            True
count_room_bath          True
count_room_bed           True
count_room_dinning       True
count_room_guest         True
count_room_kitchen       True
count_room_living        True
count_room_maid          True
count_room_storage       True
count_room_utility       True
date_created            False
date_updated            False
source                  False
url_unittype            False
day                     False
dtype: bool

In [11]:
project_df.isnull().any().any()

True

In [12]:
project_df.isnull().all()  # .all() apply AND operation to every logic value column-wise

row_number              False
unittype_id             False
project_id              False
name_th                 False
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa       False
area_usable_min         False
price_min               False
count_airconditioner    False
count_elevator           True
count_floor_internal    False
count_parking           False
count_room_bath         False
count_room_bed          False
count_room_dinning      False
count_room_guest        False
count_room_kitchen      False
count_room_living       False
count_room_maid         False
count_room_storage      False
count_room_utility      False
date_created            False
date_updated            False
source                  False
url_unittype            False
day                     False
dtype: bool

In [13]:
project_df.isnull().all() # .all() เอาค่าความจริงใน column มา and กัน

row_number              False
unittype_id             False
project_id              False
name_th                 False
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa       False
area_usable_min         False
price_min               False
count_airconditioner    False
count_elevator           True
count_floor_internal    False
count_parking           False
count_room_bath         False
count_room_bed          False
count_room_dinning      False
count_room_guest        False
count_room_kitchen      False
count_room_living       False
count_room_maid         False
count_room_storage      False
count_room_utility      False
date_created            False
date_updated            False
source                  False
url_unittype            False
day                     False
dtype: bool

###2) Delete records with missing data (dropna())

null, Nan (Not a Number), Na (Not authorised/ Not available) == missing

In [14]:
project_df.shape

(43374, 28)

In [15]:
unit_df = pd.read_csv('/content/drive/MyDrive/DPDM2023_DATA/opendata_unittype-2.csv')
unit_df.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
0,37586,unittype_35602,project_15270,Studio,2,Condo,คอนโด,NaN,30.0,3700000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:56,2020-10-14 20:21:01,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11
1,9427,unittype_4487,project_1476,ภัทรสิน,3,Townhome,ทาวน์โฮม,NaN,NaN,2000000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:17,2020-10-14 00:53:00,baania,https://baania.com/th/project/บ้านสวนทรัพย์ธาน...,2023-06-11
2,12994,unittype_37624,project_16674,Type B,3,Townhome,ทาวน์โฮม,24.0,96.0,NaN,...,NaN,NaN,NaN,NaN,NaN,2022-09-09 15:30:02,2022-09-09 15:03:18,baania,https://baania.com/th/project/สกายไลน์-อมตะ-16...,2023-06-11
3,19073,62286afcc74d880014871357,622861f7aae18f00134066d6,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,NaN,NaN,1000000.0,...,1.0,NaN,NaN,NaN,NaN,2022-03-09 16:30:04,2022-03-09 16:17:44,baania,https://baania.com/th/project/รุ่งเรืองทรัพย์ว...,2023-06-11
4,10907,unittype_8344,project_2821,2 Bedroom (ขายแล้ว),2,Condo,คอนโด,NaN,48.0,4200000.0,...,1.0,1.0,NaN,NaN,NaN,2021-11-12 13:24:53,2020-10-16 16:46:17,baania,https://baania.com/th/project/เดอะ-เทมโป-แกรนด...,2023-06-11

In [16]:
unit_df.shape

(43374, 28)

In [17]:
project_df.dropna()

Empty DataFrame
Columns: [row_number, unittype_id, project_id, name_th, propertytype_id, propertytype_name_en, propertytype_name_th, area_total_min_wa, area_usable_min, price_min, count_airconditioner, count_elevator, count_floor_internal, count_parking, count_room_bath, count_room_bed, count_room_dinning, count_room_guest, count_room_kitchen, count_room_living, count_room_maid, count_room_storage, count_room_utility, date_created, date_updated, source, url_unittype, day]
Index: []

[0 rows x 28 columns]

In [18]:
unit_df.dropna()

Empty DataFrame
Columns: [row_number, unittype_id, project_id, name_th, propertytype_id, propertytype_name_en, propertytype_name_th, area_total_min_wa, area_usable_min, price_min, count_airconditioner, count_elevator, count_floor_internal, count_parking, count_room_bath, count_room_bed, count_room_dinning, count_room_guest, count_room_kitchen, count_room_living, count_room_maid, count_room_storage, count_room_utility, date_created, date_updated, source, url_unittype, day]
Index: []

[0 rows x 28 columns]

In [19]:
project_df.dropna(axis=1)

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,date_created,date_updated,source,url_unittype,day
0,37586,unittype_35602,project_15270,Studio,2,Condo,คอนโด,2021-11-12 13:22:56,2020-10-14 20:21:01,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11
1,9427,unittype_4487,project_1476,ภัทรสิน,3,Townhome,ทาวน์โฮม,2021-11-12 13:20:17,2020-10-14 00:53:00,baania,https://baania.com/th/project/บ้านสวนทรัพย์ธาน...,2023-06-11
2,12994,unittype_37624,project_16674,Type B,3,Townhome,ทาวน์โฮม,2022-09-09 15:30:02,2022-09-09 15:03:18,baania,https://baania.com/th/project/สกายไลน์-อมตะ-16...,2023-06-11
3,19073,62286afcc74d880014871357,622861f7aae18f00134066d6,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,2022-03-09 16:30:04,2022-03-09 16:17:44,baania,https://baania.com/th/project/รุ่งเรืองทรัพย์ว...,2023-06-11
4,10907,unittype_8344,project_2821,2 Bedroom (ขายแล้ว),2,Condo,คอนโด,2021-11-12 13:24:53,2020-10-16 16:46:17,baania,https://baania.com/th/project/เดอะ-เทมโป-แกรนด...,2023-06-11
...,...,...,...,...,...,...,...,...,...,...,...,...
43369,9507,unittype_5086,project_1635,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,2022-10-19 11:30:05,2022-10-19 11:17:08,baania,https://baania.com/th/project/บ้านคุรุสภา-นครร...,2023-06-11
43370,23721,unittype_15644,project_6109,บ้านเดี่ยวสองชั้น,1,Detached House,บ้าน,2021-11-12 13:24:19,2020-10-14 23:03:19,baania,https://baania.com/th/project/บ้านเต็มสิริ-1-6...,2023-06-11
43371,31551,unittype_21385,project_8392,อาคารพาณิชย์สี่ชั้น type B,4,Commercial,อาคารพาณิชย์,2021-11-12 13:19:31,2020-10-14 00:38:09,baania,https://baania.com/th/project/พระเงิน-เพลส-839...,2023-06-11
43372,29837,unittype_26243,project_10566,ทาวน์โฮมสามชั้น,3,Townhome,ทาวน์โฮม,2020-12-04 10:47:10,2020-10-16 16:33:56,baania,https://baania.com/th/project/บ้านไทยวิลล่า-ศร...,2023-06-11
43373,9465,unittype_35686,project_15298,2 Bedroom,2,Condo,คอนโด,2023-02-28 11:00:15,2023-02-28 10:41:37,baania,https://baania.com/th/project/แกรนด์-คอนโดมิเน...,2023-06-11

In [20]:
project_df_droped = project_df.dropna(subset=['propertytype_name_en','price_min'])

In [21]:
project_df.dropna(subset=['propertytype_name_en','price_min']).isnull().any()

row_number              False
unittype_id             False
project_id              False
name_th                 False
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa        True
area_usable_min          True
price_min               False
count_airconditioner     True
count_elevator           True
count_floor_internal     True
count_parking            True
count_room_bath          True
count_room_bed           True
count_room_dinning       True
count_room_guest         True
count_room_kitchen       True
count_room_living        True
count_room_maid          True
count_room_storage       True
count_room_utility       True
date_created            False
date_updated            False
source                  False
url_unittype            False
day                     False
dtype: bool

In [22]:
#update data
project_df.dropna(subset=['propertytype_name_en','price_min'],inplace=True)

In [23]:
project_df.isnull().any()

row_number              False
unittype_id             False
project_id              False
name_th                 False
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa        True
area_usable_min          True
price_min               False
count_airconditioner     True
count_elevator           True
count_floor_internal     True
count_parking            True
count_room_bath          True
count_room_bed           True
count_room_dinning       True
count_room_guest         True
count_room_kitchen       True
count_room_living        True
count_room_maid          True
count_room_storage       True
count_room_utility       True
date_created            False
date_updated            False
source                  False
url_unittype            False
day                     False
dtype: bool

## Example

In [25]:
project_df = pd.read_csv('/content/drive/MyDrive/DPDM2023_DATA/opendata_project-2.csv')
project_df.head()

,row_number,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,price_min,developer_id,developer_name_en,...,facility_park,facility_playground,facility_pool,facility_security,date_created,date_finish,date_updated,source,url_project,day
0,20809.0,5ec3409884c1860019f3298d,Baan Laksiri Surin-Korco,บ้านหลักศิริ สุรินทร์-คอโค,3,Townhome,ทาวน์โฮม,1490000.0,developer_7326,"LAK SIRI REAL ESTATE CO., LTD.",...,NaN,NaN,1.0,1.0,2020-05-19 09:12:40,NaN,2020-12-04 10:33:10,baania,https://baania.com/th/project/บ้านหลักศิริ-สุร...,2023-06-11
1,4268.0,project_15905,Liberty Park 2,ลิเบอร์ตี้ พาร์ค 2,2,Condo,คอนโด,6500000.0,developer_10510,NaN,...,0.0,0.0,1.0,1.0,2019-06-28 16:06:45,1998-12-31 07:00:00,2020-12-04 10:39:27,baania,https://baania.com/th/project/ลิเบอร์ตี้-พาร์ค...,2023-06-11
2,5849.0,62b2b082cb0d2c0014be01a6,Pleno Paholyothin-Saimai 2,พลีโน่ พหลโยธิน-สายไหม 2,3,Townhome,ทาวน์โฮม,2790000.0,developer_1760,"AP (THAILAND) PUB CO., LTD.",...,1.0,NaN,1.0,1.0,2022-06-22 13:02:42,2024-01-01 07:00:00,2023-03-20 15:00:04,baania,https://baania.com/th/project/พลีโน่-พหลโยธิน-...,2023-06-11
3,21762.0,project_6010,Baan Thara Rin,บ้านธารารินทร์,1,Detached House,บ้าน,3100000.0,developer_10510,NaN,...,NaN,NaN,NaN,NaN,2017-04-19 14:41:10,NaN,2022-11-07 12:30:02,baania,https://baania.com/th/project/บ้านธารารินทร์-p...,2023-06-11
4,10751.0,project_11312,The Forest Hill,เดอะ ฟอเรสต์ ฮิลล์,1,Detached House,บ้าน,2450000.0,developer_7313,"Cholsiri Property Co., Ltd.",...,1.0,NaN,1.0,1.0,2017-10-30 14:10:50,2018-12-31 07:00:00,2022-08-15 16:00:05,baania,https://baania.com/th/project/เดอะ-ฟอเรสต์-ฮิล...,2023-06-11

###1) remove missing values by dropping column, find the largest column left while the ratio of missing value less than 20% (27 columns)

In [26]:
project_df.dropna(axis=1,thresh=0.8 * project_df.shape[0])

,row_number,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,price_min,developer_id,latitude,...,province_id,province_name_en,province_name_th,zipcode,count_unit,date_created,date_updated,source,url_project,day
0,20809.0,5ec3409884c1860019f3298d,Baan Laksiri Surin-Korco,บ้านหลักศิริ สุรินทร์-คอโค,3,Townhome,ทาวน์โฮม,1490000.0,developer_7326,14.896553,...,9893.0,Surin,สุรินทร์,32000.0,136.0,2020-05-19 09:12:40,2020-12-04 10:33:10,baania,https://baania.com/th/project/บ้านหลักศิริ-สุร...,2023-06-11
1,4268.0,project_15905,Liberty Park 2,ลิเบอร์ตี้ พาร์ค 2,2,Condo,คอนโด,6500000.0,developer_10510,13.746864,...,3781.0,Bangkok,กรุงเทพมหานคร,10110.0,136.0,2019-06-28 16:06:45,2020-12-04 10:39:27,baania,https://baania.com/th/project/ลิเบอร์ตี้-พาร์ค...,2023-06-11
2,5849.0,62b2b082cb0d2c0014be01a6,Pleno Paholyothin-Saimai 2,พลีโน่ พหลโยธิน-สายไหม 2,3,Townhome,ทาวน์โฮม,2790000.0,developer_1760,13.918887,...,3781.0,Bangkok,กรุงเทพมหานคร,10220.0,219.0,2022-06-22 13:02:42,2023-03-20 15:00:04,baania,https://baania.com/th/project/พลีโน่-พหลโยธิน-...,2023-06-11
3,21762.0,project_6010,Baan Thara Rin,บ้านธารารินทร์,1,Detached House,บ้าน,3100000.0,developer_10510,13.976837,...,3599.0,Pathum Thani,ปทุมธานี,12130.0,285.0,2017-04-19 14:41:10,2022-11-07 12:30:02,baania,https://baania.com/th/project/บ้านธารารินทร์-p...,2023-06-11
4,10751.0,project_11312,The Forest Hill,เดอะ ฟอเรสต์ ฮิลล์,1,Detached House,บ้าน,2450000.0,developer_7313,13.060970,...,4616.0,Chon Buri,ชลบุรี,20230.0,122.0,2017-10-30 14:10:50,2022-08-15 16:00:05,baania,https://baania.com/th/project/เดอะ-ฟอเรสต์-ฮิล...,2023-06-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23862,17534.0,project_9330,Parinyada Wongwan Sathorn,ปริญญดา วงแหวนสาทร,1,Detached House,บ้าน,4780000.0,developer_1762,13.698839,...,3781.0,Bangkok,กรุงเทพมหานคร,10160.0,175.0,2017-08-22 16:58:38,2020-12-04 10:46:24,baania,https://baania.com/th/project/ปริญญดา-วงแหวนสา...,2023-06-11
23863,12360.0,project_9316,Sinwong Garden,สินวงศ์การ์เด้น,20000,Twin house,บ้านแฝด,1280000.0,developer_10510,13.717967,...,3781.0,Bangkok,กรุงเทพมหานคร,10160.0,321.0,2017-08-22 15:19:06,2023-02-02 18:30:02,baania,https://baania.com/th/project/สินวงศ์การ์เด้น-...,2023-06-11
23864,6865.0,project_15993,La Maison Sukhumvit 22,ลาเมซอง สุขุมวิท 22,2,Condo,คอนโด,9350000.0,developer_10510,13.726415,...,3781.0,Bangkok,กรุงเทพมหานคร,10110.0,35.0,2019-07-02 15:34:11,2021-07-05 12:00:14,baania,https://baania.com/th/project/ลาเมซอง-สุขุมวิท...,2023-06-11
23865,74.0,project_105,Regent 1,รีเจ้นท์ 1,1,Detached House,บ้าน,3100000.0,developer_100,18.816591,...,1005.0,Chiang Mai,เชียงใหม่,50210.0,205.0,2015-09-23 09:06:27,2020-12-04 10:44:04,baania,https://baania.com/th/project/รีเจ้นท์-1-proje...,2023-06-11
23866,20538.0,5f2bcbd0306e7e0019068db0,Baanruenrom Nongphueng,บ้านรื่นรมย์ หนองผึ้ง,1,Detached House,บ้าน,2500000.0,developer_10510,18.710483,...,1005.0,Chiang Mai,เชียงใหม่,50140.0,18.0,2020-08-06 16:22:24,2020-12-04 10:49:31,baania,https://baania.com/th/project/บ้านรื่นรมย์-หนอ...,2023-06-11

In [27]:
project_df.dropna(axis=1,thresh=0.8 * project_df.shape[0]).dropna().shape

(18287, 30)

In [28]:
project_df.dropna(axis=1,thresh=18747.2).dropna().shape

(18287, 30)

In [29]:
project_df.dropna(axis=1,thresh=0.82015 * project_df.shape[0]).dropna().shape

(18287, 30)

In [30]:
project_df.dropna(axis=1,thresh=0.8202 * project_df.shape[0]).dropna().shape

(18287, 30)

In [31]:
0.8 * project_df.shape[0]

19093.600000000002

In [32]:
project_df.shape

(23867, 46)

###2) remove the missing values so that columns [price_min,neighborhood_name_en,developer_name_en] have missing value less than 1 value (20,738 rows)

In [35]:
pj2 = project_df.dropna(subset = ['price_min','neighborhood_name_en','developer_name_en'],thresh=2)
pj2

,row_number,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,price_min,developer_id,developer_name_en,...,facility_park,facility_playground,facility_pool,facility_security,date_created,date_finish,date_updated,source,url_project,day
0,20809.0,5ec3409884c1860019f3298d,Baan Laksiri Surin-Korco,บ้านหลักศิริ สุรินทร์-คอโค,3,Townhome,ทาวน์โฮม,1490000.0,developer_7326,"LAK SIRI REAL ESTATE CO., LTD.",...,NaN,NaN,1.0,1.0,2020-05-19 09:12:40,NaN,2020-12-04 10:33:10,baania,https://baania.com/th/project/บ้านหลักศิริ-สุร...,2023-06-11
1,4268.0,project_15905,Liberty Park 2,ลิเบอร์ตี้ พาร์ค 2,2,Condo,คอนโด,6500000.0,developer_10510,NaN,...,0.0,0.0,1.0,1.0,2019-06-28 16:06:45,1998-12-31 07:00:00,2020-12-04 10:39:27,baania,https://baania.com/th/project/ลิเบอร์ตี้-พาร์ค...,2023-06-11
2,5849.0,62b2b082cb0d2c0014be01a6,Pleno Paholyothin-Saimai 2,พลีโน่ พหลโยธิน-สายไหม 2,3,Townhome,ทาวน์โฮม,2790000.0,developer_1760,"AP (THAILAND) PUB CO., LTD.",...,1.0,NaN,1.0,1.0,2022-06-22 13:02:42,2024-01-01 07:00:00,2023-03-20 15:00:04,baania,https://baania.com/th/project/พลีโน่-พหลโยธิน-...,2023-06-11
3,21762.0,project_6010,Baan Thara Rin,บ้านธารารินทร์,1,Detached House,บ้าน,3100000.0,developer_10510,NaN,...,NaN,NaN,NaN,NaN,2017-04-19 14:41:10,NaN,2022-11-07 12:30:02,baania,https://baania.com/th/project/บ้านธารารินทร์-p...,2023-06-11
4,10751.0,project_11312,The Forest Hill,เดอะ ฟอเรสต์ ฮิลล์,1,Detached House,บ้าน,2450000.0,developer_7313,"Cholsiri Property Co., Ltd.",...,1.0,NaN,1.0,1.0,2017-10-30 14:10:50,2018-12-31 07:00:00,2022-08-15 16:00:05,baania,https://baania.com/th/project/เดอะ-ฟอเรสต์-ฮิล...,2023-06-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23862,17534.0,project_9330,Parinyada Wongwan Sathorn,ปริญญดา วงแหวนสาทร,1,Detached House,บ้าน,4780000.0,developer_1762,NaN,...,1.0,NaN,1.0,1.0,2017-08-22 16:58:38,2006-12-31 07:00:00,2020-12-04 10:46:24,baania,https://baania.com/th/project/ปริญญดา-วงแหวนสา...,2023-06-11
23863,12360.0,project_9316,Sinwong Garden,สินวงศ์การ์เด้น,20000,Twin house,บ้านแฝด,1280000.0,developer_10510,NaN,...,NaN,NaN,NaN,1.0,2017-08-22 15:19:06,NaN,2023-02-02 18:30:02,baania,https://baania.com/th/project/สินวงศ์การ์เด้น-...,2023-06-11
23864,6865.0,project_15993,La Maison Sukhumvit 22,ลาเมซอง สุขุมวิท 22,2,Condo,คอนโด,9350000.0,developer_10510,NaN,...,NaN,NaN,1.0,1.0,2019-07-02 15:34:11,1994-12-31 07:00:00,2021-07-05 12:00:14,baania,https://baania.com/th/project/ลาเมซอง-สุขุมวิท...,2023-06-11
23865,74.0,project_105,Regent 1,รีเจ้นท์ 1,1,Detached House,บ้าน,3100000.0,developer_100,"THE TROPICAL HOME CO., LTD.",...,NaN,NaN,1.0,1.0,2015-09-23 09:06:27,NaN,2020-12-04 10:44:04,baania,https://baania.com/th/project/รีเจ้นท์-1-proje...,2023-06-11
23866,20538.0,5f2bcbd0306e7e0019068db0,Baanruenrom Nongphueng,บ้านรื่นรมย์ หนองผึ้ง,1,Detached House,บ้าน,2500000.0,developer_10510,NaN,...,NaN,NaN,NaN,NaN,2020-08-06 16:22:24,2020-01-01 07:00:00,2020-12-04 10:49:31,baania,https://baania.com/th/project/บ้านรื่นรมย์-หนอ...,2023-06-11

In [36]:
pj2[['price_min','neighborhood_name_en','developer_name_en']]

       price_min          neighborhood_name_en               developer_name_en
0      1490000.0                           NaN  LAK SIRI REAL ESTATE CO., LTD.
1      6500000.0                          NANA                             NaN
2      2790000.0                        SAIMAI     AP (THAILAND) PUB CO., LTD.
3      3100000.0           LAMLUKKA KHLONG SAM                             NaN
4      2450000.0  PINTHONG INDUSTRIAL ESTATE 3     Cholsiri Property Co., Ltd.
...          ...                           ...                             ...
23862  4780000.0                     BANG KHAE                             NaN
23863  1280000.0          PHUTTHAMONTHON SAI 3                             NaN
23864  9350000.0                  SUKHUMWIT 18                             NaN
23865  3100000.0                    SANSAI NOI     THE TROPICAL HOME CO., LTD.
23866  2500000.0               NONG PHUENG TAI                             NaN

[21405 rows x 3 columns]

In [37]:
pj2[['price_min','neighborhood_name_en','developer_name_en']].dropna(thresh=2)

       price_min          neighborhood_name_en               developer_name_en
0      1490000.0                           NaN  LAK SIRI REAL ESTATE CO., LTD.
1      6500000.0                          NANA                             NaN
2      2790000.0                        SAIMAI     AP (THAILAND) PUB CO., LTD.
3      3100000.0           LAMLUKKA KHLONG SAM                             NaN
4      2450000.0  PINTHONG INDUSTRIAL ESTATE 3     Cholsiri Property Co., Ltd.
...          ...                           ...                             ...
23862  4780000.0                     BANG KHAE                             NaN
23863  1280000.0          PHUTTHAMONTHON SAI 3                             NaN
23864  9350000.0                  SUKHUMWIT 18                             NaN
23865  3100000.0                    SANSAI NOI     THE TROPICAL HOME CO., LTD.
23866  2500000.0               NONG PHUENG TAI                             NaN

[21405 rows x 3 columns]

##Replace missing value

###Replace missing value with appropriate value(introduce a new class, up to you)

In [38]:
unit_df.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
0,37586,unittype_35602,project_15270,Studio,2,Condo,คอนโด,NaN,30.0,3700000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:56,2020-10-14 20:21:01,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11
1,9427,unittype_4487,project_1476,ภัทรสิน,3,Townhome,ทาวน์โฮม,NaN,NaN,2000000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:17,2020-10-14 00:53:00,baania,https://baania.com/th/project/บ้านสวนทรัพย์ธาน...,2023-06-11
2,12994,unittype_37624,project_16674,Type B,3,Townhome,ทาวน์โฮม,24.0,96.0,NaN,...,NaN,NaN,NaN,NaN,NaN,2022-09-09 15:30:02,2022-09-09 15:03:18,baania,https://baania.com/th/project/สกายไลน์-อมตะ-16...,2023-06-11
3,19073,62286afcc74d880014871357,622861f7aae18f00134066d6,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,NaN,NaN,1000000.0,...,1.0,NaN,NaN,NaN,NaN,2022-03-09 16:30:04,2022-03-09 16:17:44,baania,https://baania.com/th/project/รุ่งเรืองทรัพย์ว...,2023-06-11
4,10907,unittype_8344,project_2821,2 Bedroom (ขายแล้ว),2,Condo,คอนโด,NaN,48.0,4200000.0,...,1.0,1.0,NaN,NaN,NaN,2021-11-12 13:24:53,2020-10-16 16:46:17,baania,https://baania.com/th/project/เดอะ-เทมโป-แกรนด...,2023-06-11

In [39]:
unit_df.fillna(0) # replace every missing value with 0

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
0,37586,unittype_35602,project_15270,Studio,2,Condo,คอนโด,0.0,30.0,3700000.0,...,0.0,0.0,0.0,0.0,0.0,2021-11-12 13:22:56,2020-10-14 20:21:01,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11
1,9427,unittype_4487,project_1476,ภัทรสิน,3,Townhome,ทาวน์โฮม,0.0,0.0,2000000.0,...,0.0,0.0,0.0,0.0,0.0,2021-11-12 13:20:17,2020-10-14 00:53:00,baania,https://baania.com/th/project/บ้านสวนทรัพย์ธาน...,2023-06-11
2,12994,unittype_37624,project_16674,Type B,3,Townhome,ทาวน์โฮม,24.0,96.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2022-09-09 15:30:02,2022-09-09 15:03:18,baania,https://baania.com/th/project/สกายไลน์-อมตะ-16...,2023-06-11
3,19073,62286afcc74d880014871357,622861f7aae18f00134066d6,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,0.0,0.0,1000000.0,...,1.0,0.0,0.0,0.0,0.0,2022-03-09 16:30:04,2022-03-09 16:17:44,baania,https://baania.com/th/project/รุ่งเรืองทรัพย์ว...,2023-06-11
4,10907,unittype_8344,project_2821,2 Bedroom (ขายแล้ว),2,Condo,คอนโด,0.0,48.0,4200000.0,...,1.0,1.0,0.0,0.0,0.0,2021-11-12 13:24:53,2020-10-16 16:46:17,baania,https://baania.com/th/project/เดอะ-เทมโป-แกรนด...,2023-06-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43369,9507,unittype_5086,project_1635,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,0.0,0.0,880000.0,...,1.0,0.0,0.0,0.0,0.0,2022-10-19 11:30:05,2022-10-19 11:17:08,baania,https://baania.com/th/project/บ้านคุรุสภา-นครร...,2023-06-11
43370,23721,unittype_15644,project_6109,บ้านเดี่ยวสองชั้น,1,Detached House,บ้าน,45.0,140.0,2400000.0,...,0.0,0.0,0.0,0.0,0.0,2021-11-12 13:24:19,2020-10-14 23:03:19,baania,https://baania.com/th/project/บ้านเต็มสิริ-1-6...,2023-06-11
43371,31551,unittype_21385,project_8392,อาคารพาณิชย์สี่ชั้น type B,4,Commercial,อาคารพาณิชย์,34.0,192.0,13000000.0,...,0.0,0.0,0.0,0.0,0.0,2021-11-12 13:19:31,2020-10-14 00:38:09,baania,https://baania.com/th/project/พระเงิน-เพลส-839...,2023-06-11
43372,29837,unittype_26243,project_10566,ทาวน์โฮมสามชั้น,3,Townhome,ทาวน์โฮม,0.0,191.0,2600000.0,...,0.0,1.0,0.0,0.0,0.0,2020-12-04 10:47:10,2020-10-16 16:33:56,baania,https://baania.com/th/project/บ้านไทยวิลล่า-ศร...,2023-06-11
43373,9465,unittype_35686,project_15298,2 Bedroom,2,Condo,คอนโด,0.0,45.0,3490000.0,...,1.0,1.0,0.0,0.0,0.0,2023-02-28 11:00:15,2023-02-28 10:41:37,baania,https://baania.com/th/project/แกรนด์-คอนโดมิเน...,2023-06-11

In [40]:
unit_df.isnull().any()

row_number              False
unittype_id             False
project_id              False
name_th                 False
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa        True
area_usable_min          True
price_min                True
count_airconditioner     True
count_elevator           True
count_floor_internal     True
count_parking            True
count_room_bath          True
count_room_bed           True
count_room_dinning       True
count_room_guest         True
count_room_kitchen       True
count_room_living        True
count_room_maid          True
count_room_storage       True
count_room_utility       True
date_created            False
date_updated            False
source                  False
url_unittype            False
day                     False
dtype: bool

In [41]:
unit_df.fillna({'count_elevator':0,'count_floor_internal':1,'price_min':'unknown'})

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
0,37586,unittype_35602,project_15270,Studio,2,Condo,คอนโด,NaN,30.0,3700000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:56,2020-10-14 20:21:01,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11
1,9427,unittype_4487,project_1476,ภัทรสิน,3,Townhome,ทาวน์โฮม,NaN,NaN,2000000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:17,2020-10-14 00:53:00,baania,https://baania.com/th/project/บ้านสวนทรัพย์ธาน...,2023-06-11
2,12994,unittype_37624,project_16674,Type B,3,Townhome,ทาวน์โฮม,24.0,96.0,unknown,...,NaN,NaN,NaN,NaN,NaN,2022-09-09 15:30:02,2022-09-09 15:03:18,baania,https://baania.com/th/project/สกายไลน์-อมตะ-16...,2023-06-11
3,19073,62286afcc74d880014871357,622861f7aae18f00134066d6,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,NaN,NaN,1000000.0,...,1.0,NaN,NaN,NaN,NaN,2022-03-09 16:30:04,2022-03-09 16:17:44,baania,https://baania.com/th/project/รุ่งเรืองทรัพย์ว...,2023-06-11
4,10907,unittype_8344,project_2821,2 Bedroom (ขายแล้ว),2,Condo,คอนโด,NaN,48.0,4200000.0,...,1.0,1.0,NaN,NaN,NaN,2021-11-12 13:24:53,2020-10-16 16:46:17,baania,https://baania.com/th/project/เดอะ-เทมโป-แกรนด...,2023-06-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43369,9507,unittype_5086,project_1635,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,NaN,880000.0,...,1.0,NaN,NaN,NaN,NaN,2022-10-19 11:30:05,2022-10-19 11:17:08,baania,https://baania.com/th/project/บ้านคุรุสภา-นครร...,2023-06-11
43370,23721,unittype_15644,project_6109,บ้านเดี่ยวสองชั้น,1,Detached House,บ้าน,45.0,140.0,2400000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:24:19,2020-10-14 23:03:19,baania,https://baania.com/th/project/บ้านเต็มสิริ-1-6...,2023-06-11
43371,31551,unittype_21385,project_8392,อาคารพาณิชย์สี่ชั้น type B,4,Commercial,อาคารพาณิชย์,34.0,192.0,13000000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:19:31,2020-10-14 00:38:09,baania,https://baania.com/th/project/พระเงิน-เพลส-839...,2023-06-11
43372,29837,unittype_26243,project_10566,ทาวน์โฮมสามชั้น,3,Townhome,ทาวน์โฮม,NaN,191.0,2600000.0,...,NaN,1.0,NaN,NaN,NaN,2020-12-04 10:47:10,2020-10-16 16:33:56,baania,https://baania.com/th/project/บ้านไทยวิลล่า-ศร...,2023-06-11
43373,9465,unittype_35686,project_15298,2 Bedroom,2,Condo,คอนโด,NaN,45.0,3490000.0,...,1.0,1.0,NaN,NaN,NaN,2023-02-28 11:00:15,2023-02-28 10:41:37,baania,https://baania.com/th/project/แกรนด์-คอนโดมิเน...,2023-06-11

In [42]:
unit_df.fillna({'count_elevator':0}).describe()

,row_number,propertytype_id,area_total_min_wa,area_usable_min,price_min,count_airconditioner,count_elevator,count_floor_internal,count_parking,count_room_bath,count_room_bed,count_room_dinning,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility
count,43374.000000,43374.000000,3148.000000,38139.000000,3.512300e+04,1759.000000,43374.0,30387.000000,24462.000000,41741.000000,41543.000000,13425.000000,12731.000000,20018.000000,10007.000000,2110.000000,4012.000000,887.000000
mean,21687.500000,1032.336446,44.888517,141.057229,5.615888e+06,2.459352,0.0,1.962616,1.865547,2.335593,2.550995,1.002160,1.011939,1.018134,1.058459,1.050237,1.055085,1.055242
std,12521.139625,4415.313079,21.790766,114.586026,1.145051e+07,1.501013,0.0,0.644954,0.768668,1.193849,1.164172,0.048007,0.111473,0.134927,0.272829,0.231140,0.271117,0.269380
min,1.000000,1.000000,1.000000,0.030000,1.000000e+05,1.000000,0.0,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,10844.250000,1.000000,23.000000,60.000000,1.950000e+06,1.000000,0.0,2.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,21687.500000,2.000000,50.000000,126.000000,3.170000e+06,2.000000,0.0,2.000000,2.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,32530.750000,3.000000,60.000000,180.000000,5.300000e+06,3.000000,0.0,2.000000,2.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,43374.000000,20000.000000,335.000000,4350.000000,5.800000e+08,10.000000,0.0,9.000000,10.000000,66.000000,10.000000,3.000000,3.000000,3.000000,5.000000,4.000000,5.000000,4.000000

In [43]:
unit_df = unit_df.fillna({'count_elevator':0})
unit_df.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
0,37586,unittype_35602,project_15270,Studio,2,Condo,คอนโด,NaN,30.0,3700000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:56,2020-10-14 20:21:01,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11
1,9427,unittype_4487,project_1476,ภัทรสิน,3,Townhome,ทาวน์โฮม,NaN,NaN,2000000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:17,2020-10-14 00:53:00,baania,https://baania.com/th/project/บ้านสวนทรัพย์ธาน...,2023-06-11
2,12994,unittype_37624,project_16674,Type B,3,Townhome,ทาวน์โฮม,24.0,96.0,NaN,...,NaN,NaN,NaN,NaN,NaN,2022-09-09 15:30:02,2022-09-09 15:03:18,baania,https://baania.com/th/project/สกายไลน์-อมตะ-16...,2023-06-11
3,19073,62286afcc74d880014871357,622861f7aae18f00134066d6,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,NaN,NaN,1000000.0,...,1.0,NaN,NaN,NaN,NaN,2022-03-09 16:30:04,2022-03-09 16:17:44,baania,https://baania.com/th/project/รุ่งเรืองทรัพย์ว...,2023-06-11
4,10907,unittype_8344,project_2821,2 Bedroom (ขายแล้ว),2,Condo,คอนโด,NaN,48.0,4200000.0,...,1.0,1.0,NaN,NaN,NaN,2021-11-12 13:24:53,2020-10-16 16:46:17,baania,https://baania.com/th/project/เดอะ-เทมโป-แกรนด...,2023-06-11

In [44]:
unit_df.isnull().any()

row_number              False
unittype_id             False
project_id              False
name_th                 False
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa        True
area_usable_min          True
price_min                True
count_airconditioner     True
count_elevator          False
count_floor_internal     True
count_parking            True
count_room_bath          True
count_room_bed           True
count_room_dinning       True
count_room_guest         True
count_room_kitchen       True
count_room_living        True
count_room_maid          True
count_room_storage       True
count_room_utility       True
date_created            False
date_updated            False
source                  False
url_unittype            False
day                     False
dtype: bool

###Replace missing value with mean

In [45]:
import numpy as np

In [46]:
np.round(unit_df['count_room_bath'].mean())

2.0

In [47]:
unit_df = unit_df.fillna({'count_room_bath':np.round(unit_df['count_room_bath'].mean())})
unit_df.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
0,37586,unittype_35602,project_15270,Studio,2,Condo,คอนโด,NaN,30.0,3700000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:56,2020-10-14 20:21:01,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11
1,9427,unittype_4487,project_1476,ภัทรสิน,3,Townhome,ทาวน์โฮม,NaN,NaN,2000000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:17,2020-10-14 00:53:00,baania,https://baania.com/th/project/บ้านสวนทรัพย์ธาน...,2023-06-11
2,12994,unittype_37624,project_16674,Type B,3,Townhome,ทาวน์โฮม,24.0,96.0,NaN,...,NaN,NaN,NaN,NaN,NaN,2022-09-09 15:30:02,2022-09-09 15:03:18,baania,https://baania.com/th/project/สกายไลน์-อมตะ-16...,2023-06-11
3,19073,62286afcc74d880014871357,622861f7aae18f00134066d6,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,NaN,NaN,1000000.0,...,1.0,NaN,NaN,NaN,NaN,2022-03-09 16:30:04,2022-03-09 16:17:44,baania,https://baania.com/th/project/รุ่งเรืองทรัพย์ว...,2023-06-11
4,10907,unittype_8344,project_2821,2 Bedroom (ขายแล้ว),2,Condo,คอนโด,NaN,48.0,4200000.0,...,1.0,1.0,NaN,NaN,NaN,2021-11-12 13:24:53,2020-10-16 16:46:17,baania,https://baania.com/th/project/เดอะ-เทมโป-แกรนด...,2023-06-11

In [48]:
unit_df.isnull().any()

row_number              False
unittype_id             False
project_id              False
name_th                 False
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa        True
area_usable_min          True
price_min                True
count_airconditioner     True
count_elevator          False
count_floor_internal     True
count_parking            True
count_room_bath         False
count_room_bed           True
count_room_dinning       True
count_room_guest         True
count_room_kitchen       True
count_room_living        True
count_room_maid          True
count_room_storage       True
count_room_utility       True
date_created            False
date_updated            False
source                  False
url_unittype            False
day                     False
dtype: bool

###Replace missing value with mean of the sub-group

In [49]:
set(unit_df['propertytype_name_en'])

{'Apartment',
 'Commercial',
 'Condo',
 'Detached House',
 'Home office',
 'Hotel',
 'Land',
 'Office Space',
 'Townhome',
 'Twin house',
 'Warehouse / Factory'}

####For Apartment

1) Filter only Apartment data

In [50]:
unit_df[unit_df['propertytype_name_en']=='Apartment'].head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
39,41766,5ebe5e1c84c1860019f324b5,5ebe5d9c84c1860019f3249f,2 Bedroom,5,Apartment,อพาตเมนต์,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:29:33,2021-01-26 11:24:48,baania,https://baania.com/th/project/นิว-นอร์ดิค-คลับ...,2023-06-11
163,3875,unittype_3048,project_414,Type B,5,Apartment,อพาตเมนต์,NaN,162.0,NaN,...,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:09,2020-10-14 00:58:47,baania,https://baania.com/th/project/บ้านราชพฤกษ์-414...,2023-06-11
2217,3873,unittype_3050,project_414,Type D,5,Apartment,อพาตเมนต์,NaN,195.0,NaN,...,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:09,2020-10-14 00:58:47,baania,https://baania.com/th/project/บ้านราชพฤกษ์-414...,2023-06-11
6411,3876,unittype_1080,project_414,Type A,5,Apartment,อพาตเมนต์,NaN,140.0,NaN,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:21:07,2020-10-14 00:58:47,baania,https://baania.com/th/project/บ้านราชพฤกษ์-414...,2023-06-11
9503,38078,unittype_1773,project_930,Studio,5,Apartment,อพาตเมนต์,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:29:57,2021-02-02 14:24:42,baania,https://baania.com/th/project/คอนโดเทรล-930/st...,2023-06-11

2) Calculate the average price_min of the group

In [51]:
unit_df[unit_df['propertytype_name_en']=='Apartment']['price_min'].mean()

1892000.0

3) Replace the mean to the missing values of the Apartment group

In [52]:
unit_df_apart = unit_df[unit_df['propertytype_name_en']=='Apartment'].fillna(
    {'price_min' : unit_df[unit_df['propertytype_name_en']=='Apartment']['price_min'].mean()})

In [54]:
unit_df_apart.isnull().any()

row_number              False
unittype_id             False
project_id              False
name_th                 False
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa        True
area_usable_min          True
price_min               False
count_airconditioner     True
count_elevator          False
count_floor_internal     True
count_parking            True
count_room_bath         False
count_room_bed           True
count_room_dinning       True
count_room_guest         True
count_room_kitchen       True
count_room_living        True
count_room_maid          True
count_room_storage       True
count_room_utility       True
date_created            False
date_updated            False
source                  False
url_unittype            False
day                     False
dtype: bool

####For Condo

In [55]:
unit_df_condo = unit_df[unit_df['propertytype_name_en']=='Condo'].fillna(
    {'price_min' : unit_df[unit_df['propertytype_name_en']=='Condo']['price_min'].mean()})

In [56]:
unit_df_condo.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
0,37586,unittype_35602,project_15270,Studio,2,Condo,คอนโด,NaN,30.00,3700000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:56,2020-10-14 20:21:01,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11
4,10907,unittype_8344,project_2821,2 Bedroom (ขายแล้ว),2,Condo,คอนโด,NaN,48.00,4200000.0,...,1.0,1.0,NaN,NaN,NaN,2021-11-12 13:24:53,2020-10-16 16:46:17,baania,https://baania.com/th/project/เดอะ-เทมโป-แกรนด...,2023-06-11
8,33884,unittype_36928,project_15818,1 Bedroom,2,Condo,คอนโด,NaN,49.00,3350000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:58,2020-10-14 20:24:11,baania,https://baania.com/th/project/ทองหล่อ-ทาวเวอร์...,2023-06-11
14,34574,unittype_37590,project_16368,4 Bedroom,2,Condo,คอนโด,NaN,170.00,15900000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:23:00,2020-10-14 20:27:19,baania,https://baania.com/th/project/จิวเวลรี่-เทรด-เ...,2023-06-11
16,39469,unittype_40049,project_17461,2 Bedroom,2,Condo,คอนโด,NaN,48.88,4700000.0,...,NaN,NaN,NaN,NaN,NaN,2023-05-11 16:00:05,2023-05-11 15:30:26,baania,https://baania.com/th/project/อะไรส์-รัชดา-19-...,2023-06-11

In [57]:
unit_df_condo.describe()

,row_number,propertytype_id,area_total_min_wa,area_usable_min,price_min,count_airconditioner,count_elevator,count_floor_internal,count_parking,count_room_bath,count_room_bed,count_room_dinning,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility
count,12806.000000,12806.0,0.0,12552.000000,1.280600e+04,559.000000,12806.0,174.000000,162.000000,12806.000000,12767.000000,3543.000000,1400.000000,5108.000000,4174.000000,97.000000,101.000000,198.0
mean,20607.232313,2.0,NaN,63.123764,6.230699e+06,1.914132,0.0,2.057471,1.160494,1.392863,1.338451,1.000847,1.005000,1.002741,1.004073,1.061856,1.108911,1.0
std,12780.814089,0.0,NaN,80.031866,1.418550e+07,0.913733,0.0,0.614964,0.567369,0.757135,0.946002,0.029091,0.080051,0.052286,0.070822,0.242145,0.507956,0.0
min,1.000000,2.0,NaN,16.000000,1.000000e+05,1.000000,0.0,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0
25%,8807.250000,2.0,NaN,30.000000,1.700000e+06,1.000000,0.0,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0
50%,21179.500000,2.0,NaN,41.000000,3.300000e+06,2.000000,0.0,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0
75%,31321.500000,2.0,NaN,63.000000,6.230699e+06,3.000000,0.0,2.000000,1.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0
max,43374.000000,2.0,NaN,4350.000000,5.800000e+08,6.000000,0.0,9.000000,4.000000,8.000000,10.000000,2.000000,3.000000,2.000000,3.000000,2.000000,5.000000,1.0

In [58]:
unit_df_apart.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
39,41766,5ebe5e1c84c1860019f324b5,5ebe5d9c84c1860019f3249f,2 Bedroom,5,Apartment,อพาตเมนต์,NaN,NaN,1892000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:29:33,2021-01-26 11:24:48,baania,https://baania.com/th/project/นิว-นอร์ดิค-คลับ...,2023-06-11
163,3875,unittype_3048,project_414,Type B,5,Apartment,อพาตเมนต์,NaN,162.0,1892000.0,...,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:09,2020-10-14 00:58:47,baania,https://baania.com/th/project/บ้านราชพฤกษ์-414...,2023-06-11
2217,3873,unittype_3050,project_414,Type D,5,Apartment,อพาตเมนต์,NaN,195.0,1892000.0,...,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:09,2020-10-14 00:58:47,baania,https://baania.com/th/project/บ้านราชพฤกษ์-414...,2023-06-11
6411,3876,unittype_1080,project_414,Type A,5,Apartment,อพาตเมนต์,NaN,140.0,1892000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:21:07,2020-10-14 00:58:47,baania,https://baania.com/th/project/บ้านราชพฤกษ์-414...,2023-06-11
9503,38078,unittype_1773,project_930,Studio,5,Apartment,อพาตเมนต์,NaN,NaN,1892000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:29:57,2021-02-02 14:24:42,baania,https://baania.com/th/project/คอนโดเทรล-930/st...,2023-06-11


##Concatenate

###Concatenate table in the Y-axis (add more data point)

In [59]:
fused_df = pd.concat([unit_df_apart,unit_df_condo])

In [60]:
fused_df

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day
39,41766,5ebe5e1c84c1860019f324b5,5ebe5d9c84c1860019f3249f,2 Bedroom,5,Apartment,อพาตเมนต์,NaN,NaN,1.892000e+06,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:29:33,2021-01-26 11:24:48,baania,https://baania.com/th/project/นิว-นอร์ดิค-คลับ...,2023-06-11
163,3875,unittype_3048,project_414,Type B,5,Apartment,อพาตเมนต์,NaN,162.0,1.892000e+06,...,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:09,2020-10-14 00:58:47,baania,https://baania.com/th/project/บ้านราชพฤกษ์-414...,2023-06-11
2217,3873,unittype_3050,project_414,Type D,5,Apartment,อพาตเมนต์,NaN,195.0,1.892000e+06,...,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:09,2020-10-14 00:58:47,baania,https://baania.com/th/project/บ้านราชพฤกษ์-414...,2023-06-11
6411,3876,unittype_1080,project_414,Type A,5,Apartment,อพาตเมนต์,NaN,140.0,1.892000e+06,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:21:07,2020-10-14 00:58:47,baania,https://baania.com/th/project/บ้านราชพฤกษ์-414...,2023-06-11
9503,38078,unittype_1773,project_930,Studio,5,Apartment,อพาตเมนต์,NaN,NaN,1.892000e+06,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:29:57,2021-02-02 14:24:42,baania,https://baania.com/th/project/คอนโดเทรล-930/st...,2023-06-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43355,17263,60488b2e582962001402e663,60488aeca8b9ee0013d7ebac,1 Bedroom,2,Condo,คอนโด,NaN,NaN,6.230699e+06,...,NaN,NaN,NaN,NaN,NaN,2021-03-10 16:30:04,2021-03-10 16:07:33,baania,https://baania.com/th/project/เดอะ-ไพรเวซี่-พา...,2023-06-11
43357,32766,unittype_32126,project_13619,1 Bedroom,2,Condo,คอนโด,NaN,31.0,6.500000e+06,...,1.0,1.0,NaN,NaN,NaN,2022-05-17 15:30:05,2022-05-17 15:17:54,baania,https://baania.com/th/project/วาลเด้น-อโศก-136...,2023-06-11
43364,12599,unittype_24778,project_9877,2 Bedroom,2,Condo,คอนโด,NaN,49.0,3.500000e+06,...,1.0,NaN,NaN,NaN,NaN,2022-08-18 15:00:06,2022-08-18 14:44:59,baania,https://baania.com/th/project/ซีซี-คอนโดมิเนีย...,2023-06-11
43366,11147,unittype_35831,project_15356,Studio,2,Condo,คอนโด,NaN,27.0,4.990000e+06,...,NaN,NaN,NaN,NaN,NaN,2022-09-22 15:00:06,2022-09-22 14:56:47,baania,https://baania.com/th/project/ไอดีโอ-โมบิ-รางน...,2023-06-11
43373,9465,unittype_35686,project_15298,2 Bedroom,2,Condo,คอนโด,NaN,45.0,3.490000e+06,...,1.0,1.0,NaN,NaN,NaN,2023-02-28 11:00:15,2023-02-28 10:41:37,baania,https://baania.com/th/project/แกรนด์-คอนโดมิเน...,2023-06-11

###Looping

In [61]:
unit_df_temp0 = unit_df[unit_df['propertytype_name_en']==list(set(unit_df['propertytype_name_en']))[0]].fillna({'price_min' : unit_df[unit_df['propertytype_name_en']==list(set(unit_df['propertytype_name_en']))[0]]['price_min'].mean()})

for group in list(set(unit_df['propertytype_name_en']))[1:]:
    print(group)
    unit_df_temp1 = unit_df[unit_df['propertytype_name_en']==group].fillna({'price_min' : unit_df[unit_df['propertytype_name_en']==group]['price_min'].mean()})
    unit_df_temp0 = pd.concat([unit_df_temp0,unit_df_temp1])

Condo
Hotel
Commercial
Warehouse / Factory
Office Space
Detached House
Home office
Land
Townhome
Twin house

In [62]:
unit_df_temp0.isnull().any()

row_number              False
unittype_id             False
project_id              False
name_th                 False
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa        True
area_usable_min          True
price_min               False
count_airconditioner     True
count_elevator          False
count_floor_internal     True
count_parking            True
count_room_bath         False
count_room_bed           True
count_room_dinning       True
count_room_guest         True
count_room_kitchen       True
count_room_living        True
count_room_maid          True
count_room_storage       True
count_room_utility       True
date_created            False
date_updated            False
source                  False
url_unittype            False
day                     False
dtype: bool

In [63]:
unit_df_temp0.shape

(43374, 28)

In [64]:
unit_df.shape

(43374, 28)

In [65]:
unit_df.isnull().any()

row_number              False
unittype_id             False
project_id              False
name_th                 False
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa        True
area_usable_min          True
price_min                True
count_airconditioner     True
count_elevator          False
count_floor_internal     True
count_parking            True
count_room_bath         False
count_room_bed           True
count_room_dinning       True
count_room_guest         True
count_room_kitchen       True
count_room_living        True
count_room_maid          True
count_room_storage       True
count_room_utility       True
date_created            False
date_updated            False
source                  False
url_unittype            False
day                     False
dtype: bool

###Concatenate table in the X-axis (adding features to the data)

Ex. map the district from the project table to the unitale

In [66]:
project_df.isnull().any()

row_number                 True
project_id                False
name_en                    True
name_th                   False
propertytype_id           False
propertytype_name_en      False
propertytype_name_th      False
price_min                  True
developer_id              False
developer_name_en          True
developer_name_th          True
latitude                  False
longitude                  True
neighborhood_id            True
neighborhood_name_en       True
neighborhood_name_th       True
subdistrict_id             True
subdistrict_name_en        True
subdistrict_name_th        True
district_id                True
district_name_en           True
district_name_th           True
province_id                True
province_name_en           True
province_name_th           True
zipcode                    True
count_elevator             True
count_elevator_service     True
count_floor                True
count_parking              True
count_tower                True
count_unit                 True
count_unittype             True
facility_clubhouse         True
facility_fitness           True
facility_meeting           True
facility_park              True
facility_playground        True
facility_pool              True
facility_security          True
date_created               True
date_finish                True
date_updated               True
source                     True
url_project                True
day                        True
dtype: bool

In [67]:
unit_df.isnull().any()

row_number              False
unittype_id             False
project_id              False
name_th                 False
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa        True
area_usable_min          True
price_min                True
count_airconditioner     True
count_elevator          False
count_floor_internal     True
count_parking            True
count_room_bath         False
count_room_bed           True
count_room_dinning       True
count_room_guest         True
count_room_kitchen       True
count_room_living        True
count_room_maid          True
count_room_storage       True
count_room_utility       True
date_created            False
date_updated            False
source                  False
url_unittype            False
day                     False
dtype: bool

In [68]:
project_df = project_df.drop_duplicates(subset=['project_id'])

In [69]:
unit_df['district_en'] = unit_df['project_id'].map(project_df.set_index('project_id')['district_name_en'])
unit_df.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,day,district_en
0,37586,unittype_35602,project_15270,Studio,2,Condo,คอนโด,NaN,30.0,3700000.0,...,NaN,NaN,NaN,NaN,2021-11-12 13:22:56,2020-10-14 20:21:01,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11,HUAI KHWANG
1,9427,unittype_4487,project_1476,ภัทรสิน,3,Townhome,ทาวน์โฮม,NaN,NaN,2000000.0,...,NaN,NaN,NaN,NaN,2021-11-12 13:20:17,2020-10-14 00:53:00,baania,https://baania.com/th/project/บ้านสวนทรัพย์ธาน...,2023-06-11,MUEANG NAKHON RATCHASIMA
2,12994,unittype_37624,project_16674,Type B,3,Townhome,ทาวน์โฮม,24.0,96.0,NaN,...,NaN,NaN,NaN,NaN,2022-09-09 15:30:02,2022-09-09 15:03:18,baania,https://baania.com/th/project/สกายไลน์-อมตะ-16...,2023-06-11,PLUAK DAENG
3,19073,62286afcc74d880014871357,622861f7aae18f00134066d6,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,NaN,NaN,1000000.0,...,NaN,NaN,NaN,NaN,2022-03-09 16:30:04,2022-03-09 16:17:44,baania,https://baania.com/th/project/รุ่งเรืองทรัพย์ว...,2023-06-11,THUNG SONG
4,10907,unittype_8344,project_2821,2 Bedroom (ขายแล้ว),2,Condo,คอนโด,NaN,48.0,4200000.0,...,1.0,NaN,NaN,NaN,2021-11-12 13:24:53,2020-10-16 16:46:17,baania,https://baania.com/th/project/เดอะ-เทมโป-แกรนด...,2023-06-11,CHOM THONG

Examples

Find average price of the detached house in Khon Kaen

In [71]:
merged_df = unit_df.merge(project_df,left_on='project_id',right_on='project_id')
merged_df.head()

,row_number_x,unittype_id,project_id,name_th_x,propertytype_id_x,propertytype_name_en_x,propertytype_name_th_x,area_total_min_wa,area_usable_min,price_min_x,...,facility_park,facility_playground,facility_pool,facility_security,date_created_y,date_finish,date_updated_y,source_y,url_project,day_y
0,37586,unittype_35602,project_15270,Studio,2,Condo,คอนโด,NaN,30.0,3700000.0,...,1.0,0.0,1.0,1.0,2019-01-31 14:05:53,2009-12-31 07:00:00,2020-12-04 10:43:09,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11
1,37585,unittype_35604,project_15270,2 Bedroom,2,Condo,คอนโด,NaN,55.0,5562000.0,...,1.0,0.0,1.0,1.0,2019-01-31 14:05:53,2009-12-31 07:00:00,2020-12-04 10:43:09,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11
2,37584,unittype_35603,project_15270,1 Bedroom,2,Condo,คอนโด,NaN,41.0,4000000.0,...,1.0,0.0,1.0,1.0,2019-01-31 14:05:53,2009-12-31 07:00:00,2020-12-04 10:43:09,baania,https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...,2023-06-11
3,9427,unittype_4487,project_1476,ภัทรสิน,3,Townhome,ทาวน์โฮม,NaN,NaN,2000000.0,...,1.0,NaN,1.0,1.0,2016-06-10 10:06:52,NaN,2020-12-04 10:38:55,baania,https://baania.com/th/project/บ้านสวนทรัพย์ธาน...,2023-06-11
4,4859,unittype_4484,project_1476,ภัทรภิรมย์,1,Detached House,บ้าน,70.0,NaN,3300000.0,...,1.0,NaN,1.0,1.0,2016-06-10 10:06:52,NaN,2020-12-04 10:38:55,baania,https://baania.com/th/project/บ้านสวนทรัพย์ธาน...,2023-06-11

In [72]:
merged_df[(merged_df['propertytype_name_th_x']=='บ้าน') & (merged_df['province_name_th']=='ขอนแก่น')]['price_min_x'].mean()

3985457.7231759657

#Create pandas df & save pandas df

##Dict-Row

In [74]:
sale = [{'account':'Jones LLC','Jan':150,'Feb':200,'Mar':140},
        {'account':'Alpha Co','Jan':200,'Feb':210,'Mar':215},
        {'account':'Blue Inc','Jan':50,'Feb':90,'Mar':95}
]

sale_tb1 = pd.DataFrame(sale)
sale_tb1

     account  Jan  Feb  Mar
0  Jones LLC  150  200  140
1   Alpha Co  200  210  215
2   Blue Inc   50   90   95

##Dict-Column

In [76]:
sales = { 'account':['Jones LLC','Alpha Co','Blue Inc'],
          'Jan'    :[150,200,50],
          'Feb'    :[200,210,90],
          'Mar'    :[140,215,95]
}
sale_tb2 = pd.DataFrame.from_dict(sales)
sale_tb2

     account  Jan  Feb  Mar
0  Jones LLC  150  200  140
1   Alpha Co  200  210  215
2   Blue Inc   50   90   95

##List-Row

In [77]:
sale = [['Jones LLC',150,200,140],
        ['Alpha Co',200,210,215],
        ['Blue Inc',50,90,90]]
labels = ['account','Jan','Feb','Mar']

sale_tb3 = pd.DataFrame.from_records(sale, columns = labels)
sale_tb3

     account  Jan  Feb  Mar
0  Jones LLC  150  200  140
1   Alpha Co  200  210  215
2   Blue Inc   50   90   90